// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AppConfigModal: typeof import('./src/components/AppConfigModal.vue')['default']
    FromTo: typeof import('./src/components/FromTo.vue')['default']
    Translator: typeof import('./src/components/Translator.vue')['default']
  }
}

export { }
